# Generated by Django 4.2.13 on 2024-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.IntegerField()),
                ('field3', models.DateField()),
                ('field4', models.CharField(max_length=200)),
                ('field5', models.TextField()),
                ('field6', models.BooleanField()),
                ('field7', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field8', models.EmailField(max_length=254)),
                ('field9', models.URLField()),
                ('field10', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile_number',
        ),
    ]
