# Generated by Django 4.2.13 on 2024-06-05 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_randomdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='randomdetail',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.profile'),
        ),
    ]
