# Generated by Django 4.2.13 on 2024-06-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_bills_delete_randomdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=200, verbose_name='Contract No.')),
                ('field2', models.CharField(max_length=200, verbose_name='Item Description')),
                ('field3', models.CharField(max_length=200, verbose_name='Invoice No.')),
                ('field4', models.CharField(max_length=200, verbose_name='Invoice Date.')),
                ('field5', models.CharField(max_length=200, verbose_name='Amount')),
                ('field6', models.CharField(max_length=200, verbose_name='Purchase Order')),
                ('field7', models.CharField(max_length=200, verbose_name='Service Entry Sheet')),
                ('field8', models.CharField(max_length=200, verbose_name='BC No.')),
                ('field9', models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], max_length=10, verbose_name='Payment Status')),
                ('field10', models.CharField(max_length=200, verbose_name='Payment Date')),
                ('field11', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Invoice pdf')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Bills',
        ),
    ]
