# Generated by Django 4.2.13 on 2024-06-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_bill_delete_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.profile'),
            preserve_default=False,
        ),
    ]
