# Generated by Django 4.2.13 on 2024-06-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_bill_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='field41',
            field=models.CharField(default=123, max_length=200, verbose_name='Vendor Name'),
            preserve_default=False,
        ),
    ]
